workflows:
  ios-testflight:
    name: iOS → TestFlight
    max_build_duration: 90
    instance_type: mac_mini_m2

    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.tuempresa.AppRecibosIA
      vars:
        XCODE_SCHEME: AppRecibosIA
        XCODE_PROJECT: AppRecibosIA.xcodeproj
      xcode: latest
      cocoapods: default

    scripts:
      - name: Install XcodeGen
        script: |
          brew install xcodegen

      - name: Generate Xcode project
        script: |
          xcodegen generate

      - name: Resolve Swift Package dependencies
        script: |
          xcodebuild -resolvePackageDependencies \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME"

      - name: Build & archive for App Store
        script: |
          xcodebuild \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphoneos \
            -configuration Release \
            -archivePath "$CM_BUILD_DIR/$XCODE_SCHEME.xcarchive" \
            archive \
            CODE_SIGN_STYLE=Automatic \
            | xcpretty

      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
            -archivePath "$CM_BUILD_DIR/$XCODE_SCHEME.xcarchive" \
            -exportOptionsPlist /Users/builder/export_options.plist \
            -exportPath "$CM_BUILD_DIR/ipa"

    artifacts:
      - $CM_BUILD_DIR/ipa/*.ipa
      - $CM_BUILD_DIR/$XCODE_SCHEME.xcarchive

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
