name: AppRecibosIA
options:
  bundleIdPrefix: com.tuempresa

targets:
  AppRecibosIA:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources: [AppRecibosIA]
    info:
      path: AppRecibosIA/Info.plist
      properties:
        NSCameraUsageDescription: "Necesitamos la cámara para escanear tus recibos."
        NSPhotoLibraryUsageDescription: "Necesitamos acceso a tus fotos para escanear recibos."
        UILaunchScreen: {}
    settings:
      base:
        SWIFT_VERSION: "5.9"
        IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    dependencies:
      - package: mlx-swift-lm
        product: MLXVLM
      - package: mlx-swift-lm
        product: MLXLMCommon

packages:
  mlx-swift-lm:
    url: https://github.com/ml-explore/mlx-swift-lm.git
    from: "2.29.1"
